# Generated by Django 5.1.3 on 2024-11-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('habitat', models.CharField(max_length=255)),
                ('diet', models.CharField(max_length=255)),
                ('avg_lifespan', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
